# 2020-09

## 01

### [ElasticBeanstalkにLaravelアプリケーションをリリースするときのebextension設定 \- Qiita](https://qiita.com/kazuhei/items/295435f367c1a5d7a6af)


ElasticBeanstalkとはAWS ElasticBeanstalkのことで、インフラを気にしないでアプリ開発ができる。サービスのこと

インフラについて

[ITインフラ（システムインフラ）とは \- IT用語辞典 e\-Words](http://e-words.jp/w/IT%E3%82%A4%E3%83%B3%E3%83%95%E3%83%A9.html)

ElasticBeanstalkにリリースする場合は、`.ebextensions/*`にconfigファイルを置くことでリリース時のコマンドを追加することができる

```
container_commands:
  01-cache_config:
    command: "php artisan config:cache"
  02-cache_route:
    command: "php artisan route:cache"
  03-cache_view:
    command: "php artisan view:cache"
```

上記はconfigとroute、viewのキャッシュをアプリケーションをアップデートシた後に生成する。

container_commandsはApacheサーバーの再起動前に実行される。

## 02

### [Promiseをthrowするのはなぜ天才的デザインなのか \- Qiita](https://qiita.com/uhyo/items/255760315ca61544fe33)

使用言語:Javascript,Typescript

PromiseをthrowするAPIデザイン

これは、コンポーネントがレンダリング時にPromiseをthrowすることでレンダリングをサスペンドしたことを表す。(Promiseが解決されるまでレンダリングできないこと)

throwは大域脱出(実行をその場で集団し、外側に制御を移す)を伴う構文で、
大域脱出することは関数から返り値を返すのを放棄すること。

関数からの返り値を放棄することで、関数の返り値の型に影響をあたえず、関数の実行を中断できる。

例

```js

function getDataOrUndefined(): string | undefined {
 // ...
}

function getData(): string {
  const maybeData = getDataOrUndefined();
  if (maybeData === undefined) {
    throw new Error("あとは任せた！！！！！！！");
  }
  // ここでは maybeData は string型
  return maybeData;
}

```

上記の`getDataOrUndefined`はデータを取得する関数で、必ずstringを返す仕様にしたい、しかし、データがなければundefinedを返す。

これをthrowは解決することが出きる。

## 03

### [Try Catch文がとらえるのは"例外"である \- Qiita](https://qiita.com/yuu_j/items/fed8f687216ef471bc97)

結論から言うと、Try Catchでなんでも解決をしようとしないこと


例

```C#
try
    {
　　　　　# a,b共に、nullになる可能性がある
        var a = GetA();
        var b = GetB();
        # 変数bのnullチェックはしていない
        if(a != null)
        {
            var aHoge = a.GetHoge();
            var bHoge = b.GetHoge();
        }
    }
    catch
    {}
```

上記のコードは変数bがnullの場合、例外が発生する。

原因は変数bのnullチェックがされていないため

個人的にはtry-catchは保険程度に書いとけばいいと思った。

try-catchの他にtry-finaliyというものがある。

try-finaliyはtryブロックで例外が発生しても、finaliyブロック内のコードは実行される。

[try\-finally \- C\# リファレンス \| Microsoft Docs](https://docs.microsoft.com/ja-jp/dotnet/csharp/language-reference/keywords/try-finally)

[【C\#】try\-catch\-finallyを使ってみよう \- Qiita](https://qiita.com/mik_claire/items/8f36d143639cd538a980)